/**
 * TheSportsDB のチーム名（英語）→ 日本語カタカナ表記マッピング。
 * DB 上の strHomeTeam / strAwayTeam に完全一致でヒットさせる。
 * 未登録の場合は原語のままフォールバック。
 */
export const TEAM_NAME_JP: Record<string, string> = {
  // ===== プレミアリーグ =====
  "Arsenal": "アーセナル",
  "Aston Villa": "アストン・ヴィラ",
  "Bournemouth": "ボーンマス",
  "Brentford": "ブレントフォード",
  "Brighton and Hove Albion": "ブライトン",
  "Burnley": "バーンリー",
  "Chelsea": "チェルシー",
  "Crystal Palace": "クリスタル・パレス",
  "Everton": "エバートン",
  "Fulham": "フラム",
  "Leeds United": "リーズ",
  "Liverpool": "リバプール",
  "Manchester City": "マンチェスター・シティ",
  "Manchester United": "マンチェスター・ユナイテッド",
  "Newcastle United": "ニューカッスル",
  "Nottingham Forest": "ノッティンガム・フォレスト",
  "Sunderland": "サンダーランド",
  "Tottenham Hotspur": "トッテナム",
  "West Ham United": "ウェストハム",
  "Wolverhampton Wanderers": "ウルブス",

  // ===== リーガ =====
  "Athletic Bilbao": "アスレティック・ビルバオ",
  "Atlético Madrid": "アトレティコ・マドリード",
  "Barcelona": "バルセロナ",
  "Celta Vigo": "セルタ",
  "Deportivo Alavés": "アラベス",
  "Elche": "エルチェ",
  "Espanyol": "エスパニョール",
  "Getafe": "ヘタフェ",
  "Girona": "ジローナ",
  "Levante": "レバンテ",
  "Mallorca": "マジョルカ",
  "Osasuna": "オサスナ",
  "Rayo Vallecano": "ラージョ",
  "Real Betis": "ベティス",
  "Real Madrid": "レアル・マドリード",
  "Real Oviedo": "レアル・オビエド",
  "Real Sociedad": "レアル・ソシエダ",
  "Sevilla": "セビージャ",
  "Valencia": "バレンシア",
  "Villarreal": "ビジャレアル",

  // ===== セリエA =====
  "AC Milan": "ミラン",
  "Atalanta": "アタランタ",
  "Bologna": "ボローニャ",
  "Cagliari": "カリアリ",
  "Como": "コモ",
  "Cremonese": "クレモネーゼ",
  "Fiorentina": "フィオレンティーナ",
  "Genoa": "ジェノア",
  "Hellas Verona": "ヴェローナ",
  "Inter Milan": "インテル",
  "Juventus": "ユベントス",
  "Lazio": "ラツィオ",
  "Lecce": "レッチェ",
  "Napoli": "ナポリ",
  "Parma": "パルマ",
  "Pisa": "ピサ",
  "Roma": "ローマ",
  "Sassuolo": "サッスオーロ",
  "Torino": "トリノ",
  "Udinese": "ウディネーゼ",

  // ===== ブンデスリーガ =====
  "Bayer Leverkusen": "レバークーゼン",
  "Bayern Munich": "バイエルン",
  "Borussia Dortmund": "ドルトムント",
  "Borussia Mönchengladbach": "ボルシアMG",
  "Eintracht Frankfurt": "フランクフルト",
  "FC Augsburg": "アウクスブルク",
  "FC Heidenheim": "ハイデンハイム",
  "FC Köln": "ケルン",
  "Freiburg": "フライブルク",
  "Hamburg": "ハンブルガーSV",
  "Hoffenheim": "ホッフェンハイム",
  "Mainz": "マインツ",
  "RB Leipzig": "RBライプツィヒ",
  "St Pauli": "ザンクト・パウリ",
  "Stuttgart": "シュトゥットガルト",
  "Union Berlin": "ウニオン・ベルリン",
  "Werder Bremen": "ブレーメン",
  "Wolfsburg": "ヴォルフスブルク",

  // ===== リーグアン =====
  "Angers": "アンジェ",
  "Auxerre": "オセール",
  "Brest": "ブレスト",
  "Le Havre": "ル・アーブル",
  "Lens": "ランス",
  "Lille": "リール",
  "Lorient": "ロリアン",
  "Lyon": "リヨン",
  "Marseille": "マルセイユ",
  "Metz": "メス",
  "Monaco": "モナコ",
  "Nantes": "ナント",
  "Nice": "ニース",
  "Paris FC": "パリFC",
  "Paris SG": "パリSG",
  "Rennes": "レンヌ",
  "Strasbourg": "ストラスブール",
  "Toulouse": "トゥールーズ",

  // ===== エールディビジ =====
  "AZ Alkmaar": "AZ",
  "Ajax": "アヤックス",
  "Excelsior": "エクセルシオール",
  "FC Volendam": "フォレンダム",
  "Feyenoord": "フェイエノールト",
  "Fortuna Sittard": "フォルトゥナ・シッタード",
  "Go Ahead Eagles": "ゴー・アヘッド・イーグルス",
  "Groningen": "フローニンゲン",
  "Heerenveen": "ヘーレンフェーン",
  "Heracles Almelo": "ヘラクレス",
  "NAC Breda": "NACブレダ",
  "NEC Nijmegen": "NECナイメヘン",
  "PEC Zwolle": "PECズボレ",
  "PSV Eindhoven": "PSV",
  "Sparta Rotterdam": "スパルタ",
  "SC Telstar": "テルスター",
  "Twente": "トゥウェンテ",
  "Utrecht": "ユトレヒト",

  // ===== ポルトガル =====
  "AVS": "AVS",
  "Alverca": "アルベルカ",
  "Arouca": "アロウカ",
  "Benfica": "ベンフィカ",
  "Braga": "ブラガ",
  "Casa Pia": "カサ・ピア",
  "Estoril Praia": "エストリル",
  "Estrela Amadora": "エストレーラ",
  "FC Porto": "ポルト",
  "Famalicao": "ファマリカン",
  "Gil Vicente": "ジル・ヴィセンテ",
  "Moreirense": "モレイレンセ",
  "Nacional de Madeira": "ナシオナル",
  "Rio Ave": "リオ・アヴェ",
  "Santa Clara": "サンタ・クララ",
  "Sporting CP": "スポルティング",
  "Tondela": "トンデラ",
  "Vitória de Guimarães": "ギマランイス",

  // ===== ベルギー =====
  "Anderlecht": "アンデルレヒト",
  "Antwerp": "アントワープ",
  "Cercle Brugge": "セルクル・ブルージュ",
  "Charleroi": "シャルルロワ",
  "Club Brugge": "クラブ・ブルージュ",
  "Dender": "デンデル",
  "Genk": "ヘンク",
  "Gent": "ヘント",
  "K Beerschot VA": "ベールスホト",
  "Mechelen": "メヘレン",
  "Oud-Heverlee Leuven": "OHルーヴェン",
  "RAAL La Louvière": "ラ・ルヴィエール",
  "Sint-Truiden": "シント＝トロイデン",
  "Sint-Truidense": "シント＝トロイデン",
  "Standard Liège": "スタンダール",
  "Union Saint-Gilloise": "ユニオンSG",
  "Westerlo": "ヴェステルロー",
  "Zulte Waregem": "ズルテ・ワレヘム",

  // ===== トルコ =====
  "Alanyaspor": "アランヤスポル",
  "Antalyaspor": "アンタルヤスポル",
  "Beşiktaş": "ベシクタシュ",
  "Eyüpspor": "エユプスポル",
  "Fatih Karagümrük": "カラギュムリュク",
  "Fenerbahçe": "フェネルバフチェ",
  "Galatasaray": "ガラタサライ",
  "Gaziantep": "ガジアンテップ",
  "Gençlerbirliği": "ゲンチレルビルリ",
  "Göztepe": "ギョズテペ",
  "Kasımpaşa": "カスムパシャ",
  "Kayserispor": "カイセリスポル",
  "Kocaelispor": "コジャエリスポル",
  "Konyaspor": "コンヤスポル",
  "Rizespor": "リゼスポル",
  "Samsunspor": "サムスンスポル",
  "Trabzonspor": "トラブゾンスポル",
  "İstanbul Başakşehir": "バシャクシェヒル",

  // ===== スコットランド =====
  "Aberdeen": "アバディーン",
  "Airdrieonians": "エアドリーオニアンズ",
  "Arbroath": "アーブロース",
  "Ayr United": "エア・ユナイテッド",
  "Celtic": "セルティック",
  "Dundee": "ダンディー",
  "Dundee United": "ダンディー・ユナイテッド",
  "Dunfermline Athletic": "ダンファームリン",
  "Falkirk": "フォルカーク",
  "Greenock Morton": "モートン",
  "Heart of Midlothian": "ハーツ",
  "Hibernian": "ハイバーニアン",
  "Kilmarnock": "キルマーノック",
  "Livingston": "リビングストン",
  "Motherwell": "マザーウェル",
  "Partick Thistle": "パーティック・シスル",
  "Queen's Park": "クイーンズ・パーク",
  "Raith Rovers": "レイス・ローヴァーズ",
  "Rangers": "レンジャーズ",
  "Ross County": "ロス・カウンティ",
  "St Johnstone": "セント・ジョンストン",
  "St Mirren": "セント・ミレン",

  // ===== スイス =====
  "Basel": "バーゼル",
  "Grasshoppers": "グラスホッパー",
  "Lausanne-Sport": "ローザンヌ",
  "Lugano": "ルガーノ",
  "Luzern": "ルツェルン",
  "Servette": "セルベット",
  "Sion": "シオン",
  "St. Gallen": "ザンクト・ガレン",
  "Thun": "トゥーン",
  "Winterthur": "ヴィンタートゥール",
  "Young Boys": "ヤング・ボーイズ",
  "Zürich": "チューリッヒ",

  // ===== オーストリア =====
  "Austria Vienna": "アウストリア・ウィーン",
  "Blau-Weiß Linz": "ブラウ＝ヴァイス・リンツ",
  "Grazer AK": "グラーツァーAK",
  "LASK": "LASK",
  "Rapid Vienna": "ラピード・ウィーン",
  "Red Bull Salzburg": "ザルツブルク",
  "SCR Altach": "アルタッハ",
  "SV Ried": "リート",
  "Sturm Graz": "シュトゥルム",
  "TSV Hartberg": "ハルトベルク",
  "WSG Tirol": "WSGティロール",
  "Wolfsberger AC": "ヴォルフスベルガー",

  // ===== UEFA その他チーム（CL/EL/ECL） =====
  "AEK Athens": "AEKアテネ",
  "AEK Larnaca": "AEKラルナカ",
  "Bodø/Glimt": "ボデ・グリムト",
  "Brann": "ブラン",
  "Breiðablik": "ブレイザブリーク",
  "Celje": "ツェリエ",
  "Crvena Zvezda": "ツルベナ・ズベズダ",
  "Dinamo Zagreb": "ディナモ・ザグレブ",
  "Drita": "ドリタ",
  "Dynamo Kyiv": "ディナモ・キエフ",
  "FC Copenhagen": "コペンハーゲン",
  "FC Midtjylland": "ミティラン",
  "FCSB": "FCSB",
  "Ferencváros": "フェレンツヴァーロシュ",
  "Hacken": "ヘッケン",
  "Jagiellonia Białystok": "ヤギェロニア",
  "Kairat Almaty": "カイラト",
  "KuPS": "KuPS",
  "Lech Poznań": "レフ・ポズナン",
  "Legia Warsaw": "レギア",
  "Lincoln Red Imps": "リンカーン",
  "Ludogorets Razgrad": "ルドゴレツ",
  "Maccabi Tel Aviv": "マッカビ・テルアビブ",
  "Malmo FF": "マルメ",
  "Noah": "ノア",
  "Olympiacos": "オリンピアコス",
  "Omonia Nicosia": "オモニア",
  "PAOK": "PAOK",
  "Pafos": "パフォス",
  "Panathinaikos": "パナシナイコス",
  "Qarabağ": "カラバフ",
  "Raków Częstochowa": "ラクフ",
  "Rijeka": "リエカ",
  "Shakhtar Donetsk": "シャフタール",
  "Shamrock Rovers": "シャムロック・ローヴァーズ",
  "Shelbourne": "シェルボーン",
  "Shkëndija": "シュケンディヤ",
  "Sigma Olomouc": "シグマ・オロモウツ",
  "Slavia Prague": "スラビア・プラハ",
  "Slovan Bratislava": "スロバン",
  "Sparta Prague": "スパルタ・プラハ",
  "Universitatea Craiova": "クライオーヴァ",
  "Viktoria Plzeň": "ヴィクトリア・プルゼニ",
  "Zrinjski Mostar": "ズリニスキ",
  "Ħamrun Spartans": "ハムルン",

  // ===== 代表 =====
  "Albania": "アルバニア代表",
  "Algeria": "アルジェリア代表",
  "Argentina": "アルゼンチン代表",
  "Armenia": "アルメニア代表",
  "Australia": "オーストラリア代表",
  "Austria": "オーストリア代表",
  "Azerbaijan": "アゼルバイジャン代表",
  "Belarus": "ベラルーシ代表",
  "Belgium": "ベルギー代表",
  "Bosnia-Herzegovina": "ボスニア代表",
  "Brazil": "ブラジル代表",
  "Bulgaria": "ブルガリア代表",
  "Canada": "カナダ代表",
  "Cape Verde": "カーボベルデ代表",
  "Colombia": "コロンビア代表",
  "Croatia": "クロアチア代表",
  "Curaçao": "キュラソー代表",
  "Cyprus": "キプロス代表",
  "Czech Republic": "チェコ代表",
  "DR Congo": "コンゴ民主共和国代表",
  "Denmark": "デンマーク代表",
  "Ecuador": "エクアドル代表",
  "Egypt": "エジプト代表",
  "England": "イングランド代表",
  "Estonia": "エストニア代表",
  "Faroe Islands": "フェロー諸島代表",
  "Finland": "フィンランド代表",
  "France": "フランス代表",
  "Georgia": "ジョージア代表",
  "Germany": "ドイツ代表",
  "Ghana": "ガーナ代表",
  "Greece": "ギリシャ代表",
  "Haiti": "ハイチ代表",
  "Hungary": "ハンガリー代表",
  "Iceland": "アイスランド代表",
  "Iran": "イラン代表",
  "Iraq": "イラク代表",
  "Ireland": "アイルランド代表",
  "Israel": "イスラエル代表",
  "Italy": "イタリア代表",
  "Ivory Coast": "コートジボワール代表",
  "Japan": "日本代表",
  "Jordan": "ヨルダン代表",
  "Kazakhstan": "カザフスタン代表",
  "Kosovo": "コソボ代表",
  "Liechtenstein": "リヒテンシュタイン代表",
  "Lithuania": "リトアニア代表",
  "Mexico": "メキシコ代表",
  "Moldova": "モルドバ代表",
  "Montenegro": "モンテネグロ代表",
  "Morocco": "モロッコ代表",
  "N.Ireland": "北アイルランド代表",
  "Netherlands": "オランダ代表",
  "New Zealand": "ニュージーランド代表",
  "Norway": "ノルウェー代表",
  "Panama": "パナマ代表",
  "Paraguay": "パラグアイ代表",
  "Poland": "ポーランド代表",
  "Portugal": "ポルトガル代表",
  "Qatar": "カタール代表",
  "Romania": "ルーマニア代表",
  "San Marino": "サンマリノ代表",
  "Saudi Arabia": "サウジアラビア代表",
  "Scotland": "スコットランド代表",
  "Senegal": "セネガル代表",
  "Serbia": "セルビア代表",
  "Slovakia": "スロバキア代表",
  "Slovenia": "スロベニア代表",
  "South Africa": "南アフリカ代表",
  "South Korea": "韓国代表",
  "Spain": "スペイン代表",
  "Sweden": "スウェーデン代表",
  "Switzerland": "スイス代表",
  "Tunisia": "チュニジア代表",
  "Turkey": "トルコ代表",
  "USA": "アメリカ代表",
  "Ukraine": "ウクライナ代表",
  "Uruguay": "ウルグアイ代表",
  "Uzbekistan": "ウズベキスタン代表",
  "Wales": "ウェールズ代表",
};

/** チーム名を日本語表記に。未登録時は原語をそのまま返す。 */
export function teamNameJp(rawName: string | null | undefined): string {
  if (!rawName) return "";
  return TEAM_NAME_JP[rawName] ?? rawName;
}

/**
 * リーグ／大会の表示名（カタカナ寄せ）。
 * UEFA 大会の略称は正式表記に展開し、リーグはカタカナ正式名で揃える。
 */
export const LEAGUE_DISPLAY_JP: Record<string, string> = {
  プレミアリーグ: "プレミアリーグ",
  リーガ: "ラ・リーガ",
  セリエA: "セリエA",
  ブンデスリーガ: "ブンデスリーガ",
  リーグアン: "リーグ・アン",
  エールディビジ: "エールディビジ",
  ポルトガル: "プリメイラ・リーガ",
  ベルギー: "ジュピラー・プロ・リーグ",
  トルコ: "シュペル・リグ",
  スコットランド: "スコティッシュ・プレミアシップ",
  スイス: "スーパー・リーグ",
  オーストリア: "ブンデスリーガ（オーストリア）",
  CL: "チャンピオンズリーグ",
  EL: "ヨーロッパリーグ",
  ECL: "カンファレンスリーグ",
  W杯予選: "ワールドカップ予選",
  EURO: "EURO",
  ネーションズリーグ: "ネーションズリーグ",
  "親善試合/その他": "親善試合",
};

export function leagueDisplayJp(nameJp: string | null | undefined): string {
  if (!nameJp) return "";
  return LEAGUE_DISPLAY_JP[nameJp] ?? nameJp;
}
