/**
 * TheSportsDB のチーム名（英語）→ 日本語カタカナ表記マッピング。
 * DB 上の strHomeTeam / strAwayTeam に完全一致でヒットさせる。
 * 未登録の場合は原語のままフォールバック。
 */
export const TEAM_NAME_JP: Record<string, string> = {
  // ===== プレミアリーグ =====
  "Arsenal": "アーセナル",
  "Aston Villa": "アストン・ヴィラ",
  "Bournemouth": "ボーンマス",
  "Brentford": "ブレントフォード",
  "Brighton and Hove Albion": "ブライトン",
  "Burnley": "バーンリー",
  "Chelsea": "チェルシー",
  "Crystal Palace": "クリスタル・パレス",
  "Everton": "エバートン",
  "Fulham": "フラム",
  "Leeds United": "リーズ",
  "Liverpool": "リバプール",
  "Manchester City": "マンチェスター・シティ",
  "Manchester United": "マンチェスター・ユナイテッド",
  "Newcastle United": "ニューカッスル",
  "Nottingham Forest": "ノッティンガム・フォレスト",
  "Sunderland": "サンダーランド",
  "Tottenham Hotspur": "トッテナム",
  "West Ham United": "ウェストハム",
  "Wolverhampton Wanderers": "ウルブス",

  // ===== リーガ =====
  "Athletic Bilbao": "アスレティック・ビルバオ",
  "Atlético Madrid": "アトレティコ・マドリード",
  "Barcelona": "バルセロナ",
  "Celta Vigo": "セルタ",
  "Deportivo Alavés": "アラベス",
  "Elche": "エルチェ",
  "Espanyol": "エスパニョール",
  "Getafe": "ヘタフェ",
  "Girona": "ジローナ",
  "Levante": "レバンテ",
  "Mallorca": "マジョルカ",
  "Osasuna": "オサスナ",
  "Rayo Vallecano": "ラージョ",
  "Real Betis": "ベティス",
  "Real Madrid": "レアル・マドリード",
  "Real Oviedo": "レアル・オビエド",
  "Real Sociedad": "レアル・ソシエダ",
  "Sevilla": "セビージャ",
  "Valencia": "バレンシア",
  "Villarreal": "ビジャレアル",

  // ===== セリエA =====
  "AC Milan": "ミラン",
  "Atalanta": "アタランタ",
  "Bologna": "ボローニャ",
  "Cagliari": "カリアリ",
  "Como": "コモ",
  "Cremonese": "クレモネーゼ",
  "Fiorentina": "フィオレンティーナ",
  "Genoa": "ジェノア",
  "Hellas Verona": "ヴェローナ",
  "Inter Milan": "インテル",
  "Juventus": "ユベントス",
  "Lazio": "ラツィオ",
  "Lecce": "レッチェ",
  "Napoli": "ナポリ",
  "Parma": "パルマ",
  "Pisa": "ピサ",
  "Roma": "ローマ",
  "Sassuolo": "サッスオーロ",
  "Torino": "トリノ",
  "Udinese": "ウディネーゼ",

  // ===== ブンデスリーガ =====
  "Bayer Leverkusen": "レバークーゼン",
  "Bayern Munich": "バイエルン",
  "Borussia Dortmund": "ドルトムント",
  "Borussia Mönchengladbach": "ボルシアMG",
  "Eintracht Frankfurt": "フランクフルト",
  "FC Augsburg": "アウクスブルク",
  "FC Heidenheim": "ハイデンハイム",
  "FC Köln": "ケルン",
  "Freiburg": "フライブルク",
  "Hamburg": "ハンブルガーSV",
  "Hoffenheim": "ホッフェンハイム",
  "Mainz": "マインツ",
  "RB Leipzig": "RBライプツィヒ",
  "St Pauli": "ザンクト・パウリ",
  "Stuttgart": "シュトゥットガルト",
  "Union Berlin": "ウニオン・ベルリン",
  "Werder Bremen": "ブレーメン",
  "Wolfsburg": "ヴォルフスブルク",

  // ===== リーグアン =====
  "Angers": "アンジェ",
  "Auxerre": "オセール",
  "Brest": "ブレスト",
  "Le Havre": "ル・アーブル",
  "Lens": "ランス",
  "Lille": "リール",
  "Lorient": "ロリアン",
  "Lyon": "リヨン",
  "Marseille": "マルセイユ",
  "Metz": "メス",
  "Monaco": "モナコ",
  "Nantes": "ナント",
  "Nice": "ニース",
  "Paris FC": "パリFC",
  "Paris SG": "パリSG",
  "Rennes": "レンヌ",
  "Strasbourg": "ストラスブール",
  "Toulouse": "トゥールーズ",

  // ===== エールディビジ =====
  "AZ Alkmaar": "AZ",
  "Ajax": "アヤックス",
  "Excelsior": "エクセルシオール",
  "FC Volendam": "フォレンダム",
  "Feyenoord": "フェイエノールト",
  "Fortuna Sittard": "フォルトゥナ・シッタード",
  "Go Ahead Eagles": "ゴー・アヘッド・イーグルス",
  "Groningen": "フローニンゲン",
  "Heerenveen": "ヘーレンフェーン",
  "Heracles Almelo": "ヘラクレス",
  "NAC Breda": "NACブレダ",
  "NEC Nijmegen": "NECナイメヘン",
  "PEC Zwolle": "PECズボレ",
  "PSV Eindhoven": "PSV",
  "Sparta Rotterdam": "スパルタ",
  "SC Telstar": "テルスター",
  "Twente": "トゥウェンテ",
  "Utrecht": "ユトレヒト",

  // ===== ポルトガル =====
  "AVS": "AVS",
  "Alverca": "アルベルカ",
  "Arouca": "アロウカ",
  "Benfica": "ベンフィカ",
  "Braga": "ブラガ",
  "Casa Pia": "カサ・ピア",
  "Estoril Praia": "エストリル",
  "Estrela Amadora": "エストレーラ",
  "FC Porto": "ポルト",
  "Famalicao": "ファマリカン",
  "Gil Vicente": "ジル・ヴィセンテ",
  "Moreirense": "モレイレンセ",
  "Nacional de Madeira": "ナシオナル",
  "Rio Ave": "リオ・アヴェ",
  "Santa Clara": "サンタ・クララ",
  "Sporting CP": "スポルティング",
  "Tondela": "トンデラ",
  "Vitória de Guimarães": "ギマランイス",

  // ===== ベルギー =====
  "Anderlecht": "アンデルレヒト",
  "Antwerp": "アントワープ",
  "Cercle Brugge": "セルクル・ブルージュ",
  "Charleroi": "シャルルロワ",
  "Club Brugge": "クラブ・ブルージュ",
  "Dender": "デンデル",
  "Genk": "ヘンク",
  "Gent": "ヘント",
  "K Beerschot VA": "ベールスホト",
  "Mechelen": "メヘレン",
  "Oud-Heverlee Leuven": "OHルーヴェン",
  "RAAL La Louvière": "ラ・ルヴィエール",
  "Sint-Truiden": "シント＝トロイデン",
  "Sint-Truidense": "シント＝トロイデン",
  "Standard Liège": "スタンダール",
  "Union Saint-Gilloise": "ユニオンSG",
  "Westerlo": "ヴェステルロー",
  "Zulte Waregem": "ズルテ・ワレヘム",

  // ===== トルコ =====
  "Alanyaspor": "アランヤスポル",
  "Antalyaspor": "アンタルヤスポル",
  "Beşiktaş": "ベシクタシュ",
  "Eyüpspor": "エユプスポル",
  "Fatih Karagümrük": "カラギュムリュク",
  "Fenerbahçe": "フェネルバフチェ",
  "Galatasaray": "ガラタサライ",
  "Gaziantep": "ガジアンテップ",
  "Gençlerbirliği": "ゲンチレルビルリ",
  "Göztepe": "ギョズテペ",
  "Kasımpaşa": "カスムパシャ",
  "Kayserispor": "カイセリスポル",
  "Kocaelispor": "コジャエリスポル",
  "Konyaspor": "コンヤスポル",
  "Rizespor": "リゼスポル",
  "Samsunspor": "サムスンスポル",
  "Trabzonspor": "トラブゾンスポル",
  "İstanbul Başakşehir": "バシャクシェヒル",

  // ===== スコットランド =====
  "Aberdeen": "アバディーン",
  "Airdrieonians": "エアドリーオニアンズ",
  "Arbroath": "アーブロース",
  "Ayr United": "エア・ユナイテッド",
  "Celtic": "セルティック",
  "Dundee": "ダンディー",
  "Dundee United": "ダンディー・ユナイテッド",
  "Dunfermline Athletic": "ダンファームリン",
  "Falkirk": "フォルカーク",
  "Greenock Morton": "モートン",
  "Heart of Midlothian": "ハーツ",
  "Hibernian": "ハイバーニアン",
  "Kilmarnock": "キルマーノック",
  "Livingston": "リビングストン",
  "Motherwell": "マザーウェル",
  "Partick Thistle": "パーティック・シスル",
  "Queen's Park": "クイーンズ・パーク",
  "Raith Rovers": "レイス・ローヴァーズ",
  "Rangers": "レンジャーズ",
  "Ross County": "ロス・カウンティ",
  "St Johnstone": "セント・ジョンストン",
  "St Mirren": "セント・ミレン",

  // ===== スイス =====
  "Basel": "バーゼル",
  "Grasshoppers": "グラスホッパー",
  "Lausanne-Sport": "ローザンヌ",
  "Lugano": "ルガーノ",
  "Luzern": "ルツェルン",
  "Servette": "セルベット",
  "Sion": "シオン",
  "St. Gallen": "ザンクト・ガレン",
  "Thun": "トゥーン",
  "Winterthur": "ヴィンタートゥール",
  "Young Boys": "ヤング・ボーイズ",
  "Zürich": "チューリッヒ",

  // ===== オーストリア =====
  "Austria Vienna": "アウストリア・ウィーン",
  "Blau-Weiß Linz": "ブラウ＝ヴァイス・リンツ",
  "Grazer AK": "グラーツァーAK",
  "LASK": "LASK",
  "Rapid Vienna": "ラピード・ウィーン",
  "Red Bull Salzburg": "ザルツブルク",
  "SCR Altach": "アルタッハ",
  "SV Ried": "リート",
  "Sturm Graz": "シュトゥルム",
  "TSV Hartberg": "ハルトベルク",
  "WSG Tirol": "WSGティロール",
  "Wolfsberger AC": "ヴォルフスベルガー",

  // ===== UEFA その他チーム（CL/EL/ECL） =====
  "AEK Athens": "AEKアテネ",
  "AEK Larnaca": "AEKラルナカ",
  "Bodø/Glimt": "ボデ・グリムト",
  "Brann": "ブラン",
  "Breiðablik": "ブレイザブリーク",
  "Celje": "ツェリエ",
  "Crvena Zvezda": "ツルベナ・ズベズダ",
  "Dinamo Zagreb": "ディナモ・ザグレブ",
  "Drita": "ドリタ",
  "Dynamo Kyiv": "ディナモ・キエフ",
  "FC Copenhagen": "コペンハーゲン",
  "FC Midtjylland": "ミティラン",
  "FCSB": "FCSB",
  "Ferencváros": "フェレンツヴァーロシュ",
  "Hacken": "ヘッケン",
  "Jagiellonia Białystok": "ヤギェロニア",
  "Kairat Almaty": "カイラト",
  "KuPS": "KuPS",
  "Lech Poznań": "レフ・ポズナン",
  "Legia Warsaw": "レギア",
  "Lincoln Red Imps": "リンカーン",
  "Ludogorets Razgrad": "ルドゴレツ",
  "Maccabi Tel Aviv": "マッカビ・テルアビブ",
  "Malmo FF": "マルメ",
  "Noah": "ノア",
  "Olympiacos": "オリンピアコス",
  "Omonia Nicosia": "オモニア",
  "PAOK": "PAOK",
  "Pafos": "パフォス",
  "Panathinaikos": "パナシナイコス",
  "Qarabağ": "カラバフ",
  "Raków Częstochowa": "ラクフ",
  "Rijeka": "リエカ",
  "Shakhtar Donetsk": "シャフタール",
  "Shamrock Rovers": "シャムロック・ローヴァーズ",
  "Shelbourne": "シェルボーン",
  "Shkëndija": "シュケンディヤ",
  "Sigma Olomouc": "シグマ・オロモウツ",
  "Slavia Prague": "スラビア・プラハ",
  "Slovan Bratislava": "スロバン",
  "Sparta Prague": "スパルタ・プラハ",
  "Universitatea Craiova": "クライオーヴァ",
  "Viktoria Plzeň": "ヴィクトリア・プルゼニ",
  "Zrinjski Mostar": "ズリニスキ",
  "Ħamrun Spartans": "ハムルン",

  // ===== 代表 =====
  "Albania": "アルバニア代表",
  "Algeria": "アルジェリア代表",
  "Argentina": "アルゼンチン代表",
  "Armenia": "アルメニア代表",
  "Australia": "オーストラリア代表",
  "Austria": "オーストリア代表",
  "Azerbaijan": "アゼルバイジャン代表",
  "Belarus": "ベラルーシ代表",
  "Belgium": "ベルギー代表",
  "Bosnia-Herzegovina": "ボスニア代表",
  "Brazil": "ブラジル代表",
  "Bulgaria": "ブルガリア代表",
  "Canada": "カナダ代表",
  "Cape Verde": "カーボベルデ代表",
  "Colombia": "コロンビア代表",
  "Croatia": "クロアチア代表",
  "Curaçao": "キュラソー代表",
  "Cyprus": "キプロス代表",
  "Czech Republic": "チェコ代表",
  "DR Congo": "コンゴ民主共和国代表",
  "Denmark": "デンマーク代表",
  "Ecuador": "エクアドル代表",
  "Egypt": "エジプト代表",
  "England": "イングランド代表",
  "Estonia": "エストニア代表",
  "Faroe Islands": "フェロー諸島代表",
  "Finland": "フィンランド代表",
  "France": "フランス代表",
  "Georgia": "ジョージア代表",
  "Germany": "ドイツ代表",
  "Ghana": "ガーナ代表",
  "Greece": "ギリシャ代表",
  "Haiti": "ハイチ代表",
  "Hungary": "ハンガリー代表",
  "Iceland": "アイスランド代表",
  "Iran": "イラン代表",
  "Iraq": "イラク代表",
  "Ireland": "アイルランド代表",
  "Israel": "イスラエル代表",
  "Italy": "イタリア代表",
  "Ivory Coast": "コートジボワール代表",
  "Japan": "日本代表",
  "Jordan": "ヨルダン代表",
  "Kazakhstan": "カザフスタン代表",
  "Kosovo": "コソボ代表",
  "Liechtenstein": "リヒテンシュタイン代表",
  "Lithuania": "リトアニア代表",
  "Mexico": "メキシコ代表",
  "Moldova": "モルドバ代表",
  "Montenegro": "モンテネグロ代表",
  "Morocco": "モロッコ代表",
  "N.Ireland": "北アイルランド代表",
  "Netherlands": "オランダ代表",
  "New Zealand": "ニュージーランド代表",
  "Norway": "ノルウェー代表",
  "Panama": "パナマ代表",
  "Paraguay": "パラグアイ代表",
  "Poland": "ポーランド代表",
  "Portugal": "ポルトガル代表",
  "Qatar": "カタール代表",
  "Romania": "ルーマニア代表",
  "San Marino": "サンマリノ代表",
  "Saudi Arabia": "サウジアラビア代表",
  "Scotland": "スコットランド代表",
  "Senegal": "セネガル代表",
  "Serbia": "セルビア代表",
  "Slovakia": "スロバキア代表",
  "Slovenia": "スロベニア代表",
  "South Africa": "南アフリカ代表",
  "South Korea": "韓国代表",
  "Spain": "スペイン代表",
  "Sweden": "スウェーデン代表",
  "Switzerland": "スイス代表",
  "Tunisia": "チュニジア代表",
  "Turkey": "トルコ代表",
  "USA": "アメリカ代表",
  "Ukraine": "ウクライナ代表",
  "Uruguay": "ウルグアイ代表",
  "Uzbekistan": "ウズベキスタン代表",
  "Wales": "ウェールズ代表",

  // ===== FAカップ（イングランド下部リーグ） =====
  "Accrington": "アクリントン",
  "AFC Fylde": "AFCフィルド",
  "AFC Wimbledon": "AFCウィンブルドン",
  "Aldershot": "オルダーショット",
  "Alfreton Town": "アルフレトン",
  "Altrincham": "オルトリンチャム",
  "Barnet": "バーネット",
  "Barnsley": "バーンズリー",
  "Barrow": "バロー",
  "Bath City": "バース・シティ",
  "Biggleswade": "ビグルズウェイド",
  "Birmingham": "バーミンガム",
  "Bishops Stortford": "ビショップス・ストートフォード",
  "Blackburn": "ブラックバーン",
  "Blackpool": "ブラックプール",
  "Bolton": "ボルトン",
  "Boreham Wood": "ボアハム・ウッド",
  "Boston United FC": "ボストン・ユナイテッド",
  "Brackley Town": "ブラックリー",
  "Bradford": "ブラッドフォード",
  "Braintree Town": "ブレインツリー",
  "Brighton": "ブライトン",
  "Bristol City": "ブリストル・シティ",
  "Bristol Rovers": "ブリストル・ローバーズ",
  "Bromley": "ブロムリー",
  "Burton": "バートン",
  "Bury": "ベリー",
  "Cambridge United": "ケンブリッジ",
  "Cardiff": "カーディフ",
  "Carlisle": "カーライル",
  "Carshalton Athletic": "カーシャルトン",
  "Charlton": "チャールトン",
  "Chelmsford": "チェルムズフォード",
  "Cheltenham": "チェルトナム",
  "Chertsey Town": "チャーツィー",
  "Chesham United": "チェシャム",
  "Chester City": "チェスター",
  "Chesterfield": "チェスターフィールド",
  "Colchester": "コルチェスター",
  "Coventry": "コベントリー",
  "Crawley": "クローリー",
  "Cray Wanderers": "クレイ・ワンダラーズ",
  "Crewe": "クルー",
  "Curzon": "カーゾン",
  "Dagenham and Redbridge": "ダゲナム",
  "Derby": "ダービー",
  "Doncaster": "ドンカスター",
  "Ebbsfleet United": "エブスフリート",
  "Eastleigh": "イーストリー",
  "Exeter": "エクセター",
  "Farsley Celtic": "ファーズリー",
  "Fleetwood Town": "フリートウッド",
  "Forest Green Rovers": "フォレスト・グリーン",
  "Gainsborough": "ゲインズバラ",
  "Gateshead FC": "ゲーツヘッド",
  "Gillingham": "ギリンガム",
  "Gorleston": "ゴールストン",
  "Gosport Borough": "ゴスポート",
  "Grimsby": "グリムズビー",
  "Guiseley": "ガイズリー",
  "Halifax": "ハリファックス",
  "Harborough Town": "ハーバラ",
  "Harrogate Town FC": "ハロゲート",
  "Hartlepool": "ハートリプール",
  "Hednesford Town": "ヘドネスフォード",
  "Hornchurch": "ホーンチャーチ",
  "Horsham": "ホーシャム",
  "Huddersfield Town": "ハダーズフィールド",
  "Hull": "ハル",
  "Ipswich": "イプスウィッチ",
  "Kettering Town": "ケタリング",
  "Kidderminster Harriers": "キダーミンスター",
  "Kings Lynn Town": "キングス・リン",
  "Leeds": "リーズ",
  "Leicester": "レスター",
  "Leiston": "レイストン",
  "Leyton Orient": "レイトン・オリエント",
  "Lincoln": "リンカーン",
  "Lowestoft Town": "ローストフト",
  "Luton": "ルートン",
  "Macclesfield": "マクルズフィールド",
  "Maidenhead United": "メイデンヘッド",
  "Maidstone": "メイドストーン",
  "Mansfield": "マンスフィールド",
  "Middlesbrough": "ミドルズブラ",
  "Millwall": "ミルウォール",
  "Milton Keynes Dons": "MKドンズ",
  "Morecambe": "モアカム",
  "Newcastle": "ニューカッスル",
  "Newport": "ニューポート",
  "Northampton": "ノーザンプトン",
  "Norwich": "ノリッジ",
  "Notts County": "ノッツ・カウンティ",
  "Oldham": "オールダム",
  "Oxford Utd": "オックスフォード",
  "Peterboro": "ピーターバラ",
  "Peterborough Sports": "ピーターバラ・スポーツ",
  "Plymouth": "プリマス",
  "Plymouth Parkway": "プリマス・パークウェイ",
  "Port Vale": "ポート・ヴェール",
  "Portsmouth": "ポーツマス",
  "Preston": "プレストン",
  "QPR": "クイーンズ・パーク・レンジャーズ",
  "Reading": "レディング",
  "Rochdale": "ロッチデール",
  "Rotherham": "ロザラム",
  "Rushall Olympic": "ラッシャル",
  "Salford City": "サルフォード",
  "Scarborough Athletic": "スカーバラ",
  "Sheffield United": "シェフィールド・ユナイテッド",
  "Sheffield Weds": "シェフィールド・ウェンズデー",
  "Shrewsbury": "シュルーズベリー",
  "Slough Town": "スラウ",
  "Solihull Moors": "ソリハル",
  "Southampton": "サウサンプトン",
  "Southend": "サウゼンド",
  "Spennymoor Town FC": "スペニームア",
  "Stevenage": "スティーブネージ",
  "Stockport": "ストックポート",
  "Stoke": "ストーク",
  "Sutton United": "サットン",
  "Swansea": "スウォンジー",
  "Swindon": "スウィンドン",
  "Tamworth": "タムワース",
  "Taunton Town": "トーントン",
  "Tonbridge Angels": "トンブリッジ",
  "Tottenham": "トッテナム",
  "Tranmere": "トランミア",
  "Walsall": "ウォルソール",
  "Watford": "ワトフォード",
  "Wealdstone": "ウィールドストーン",
  "West Brom": "ウェスト・ブロム",
  "West Ham": "ウェストハム",
  "Weston-super-Mare FC": "ウェストン・スーパー・メア",
  "Weymouth": "ウェイマス",
  "Wigan": "ウィガン",
  "Woking": "ウォーキング",
  "Wolves": "ウルブス",
  "Worthing": "ワージング",
  "Wrexham": "レクサム",
  "Wycombe": "ウィコム",
  "York": "ヨーク",

  // ===== コパ・デル・レイ（スペイン下部リーグ） =====
  "AD Ceuta FC": "セウタ",
  "Alaves": "アラベス",
  "Albacete": "アルバセテ",
  "Alcorcon": "アルコルコン",
  "Alfaro": "アルファロ",
  "Almeria": "アルメリア",
  "Astur": "アストゥル",
  "Atletico Madrid": "アトレティコ・マドリード",
  "Atlético Paso": "アトレティコ・パソ",
  "Barakaldo": "バラカルド",
  "Barbastro": "バルバストロ",
  "Beasain": "ベアサイン",
  "Bergantiños": "ベルガンティニョス",
  "Burgos": "ブルゴス",
  "CD Ciudad de Lucena": "シウダー・デ・ルセナ",
  "CD Coria": "コリア",
  "CD Ibiza Islas Pitiusas": "イビサ",
  "CD Móstoles URJC": "モストレス",
  "CE Europa": "エウロパ",
  "CF Badalona": "バダロナ",
  "Cacereño": "カセレニョ",
  "Cadiz": "カディス",
  "Cartagena FC": "カルタヘナ",
  "Castellón": "カステジョン",
  "Chiclana": "チクラナ",
  "Compostela": "コンポステーラ",
  "Comtal": "コンタル",
  "Conquense": "コンクエンセ",
  "Cordoba": "コルドバ",
  "Cortes": "コルテス",
  "Cuarte": "クアルテ",
  "Deportiva Minera": "デポルティバ・ミネラ",
  "Don Benito": "ドン・ベニート",
  "Eibar": "エイバル",
  "Eldense": "エルデンセ",
  "Escobedo": "エスコベド",
  "Estepona": "エステポナ",
  "FC Andorra": "FCアンドラ",
  "Gimnastic": "ヒムナスティック",
  "Gimnástica Segoviana CF": "ヒムナスティカ・セゴビアナ",
  "Granada": "グラナダ",
  "Guijuelo": "ギフエロ",
  "Gévora": "ヘボラ",
  "Hercules": "エルクレス",
  "Huesca": "ウエスカ",
  "L-'Hospitalet": "ロスピタレット",
  "La Coruna": "ラ・コルーニャ",
  "Langreo": "ランレオ",
  "Lanzarote": "ランサローテ",
  "Laredo": "ラレド",
  "Las Palmas": "ラス・パルマス",
  "Las Rozas CF": "ラス・ロサス",
  "Leganes": "レガネス",
  "Leonesa": "レオネサ",
  "Lleida Esportiu": "ジェイダ",
  "Malaga": "マラガ",
  "Marbella": "マルベジャ",
  "Mirandes": "ミランデス",
  "Numancia": "ヌマンシア",
  "Olot": "オロット",
  "Ontiñena": "オンティニェナ",
  "Orihuela": "オリウエラ",
  "Ourense": "オウレンセ",
  "Poblense": "ポブレンセ",
  "Ponferradina": "ポンフェラーディナ",
  "Pontevedra": "ポンテベドラ",
  "Racing Club de Ferrol": "フェロル",
  "Real Jaén": "レアル・ハエン",
  "Real Ávila": "レアル・アビラ",
  "SD Amorebieta": "アモレビエタ",
  "SD Ejea": "エヘア",
  "SS Reyes": "SSレジェス",
  "Salamanca UDS": "サラマンカ",
  "San Tirso": "サン・ティルソ",
  "Sant Andreu": "サン・アンドレウ",
  "Santander": "サンタンデール",
  "Sp Gijon": "スポルティング・ヒホン",
  "Tenerife": "テネリフェ",
  "Tudelano": "トゥデラノ",
  "UD Ibiza": "UDイビサ",
  "UD Llanera": "ジャネラ",
  "UD Logroñés": "ログロニェス",
  "UD San Pedro": "サン・ペドロ",
  "Unionistas de Salamanca": "ウニオニスタス",
  "Utebo": "ウテボ",
  "Valladolid": "バジャドリード",
  "Vallecano": "バジェカノ",
  "Vic": "ビック",
  "Villamuriel": "ビジャムリエル",
  "Xerez": "ヘレス",
  "Yeclano": "イェクラノ",
  "Zamora": "サモラ",
  "Zaragoza": "サラゴサ",
  "Águilas": "アギラス",

  // ===== コッパ・イタリア（イタリア下部リーグ） =====
  "Avellino": "アベッリーノ",
  "Bari": "バーリ",
  "Brescia": "ブレシア",
  "Calcio Padova": "パドヴァ",
  "Carrarese": "カッラレーゼ",
  "Catania": "カターニア",
  "Catanzaro": "カタンザーロ",
  "Cesena": "チェゼーナ",
  "Cittadella": "チッタデッラ",
  "Cosenza": "コゼンツァ",
  "Empoli": "エンポリ",
  "Frosinone": "フロジノーネ",
  "Juve Stabia": "ユーヴェ・スタービア",
  "Mantova": "マントヴァ",
  "Modena": "モデナ",
  "Monza": "モンツァ",
  "Palermo": "パレルモ",
  "Parma Calcio 1913": "パルマ",
  "Reggiana": "レッジャーナ",
  "Salernitana": "サレルニターナ",
  "Sampdoria": "サンプドリア",
  "Sassari Torres": "トッレス",
  "Spezia": "スペツィア",
  "Sudtirol": "ジュートティロル",
  "Venezia": "ヴェネツィア",
  "Verona": "ヴェローナ",

  // ===== DFBポカール（ドイツ下部リーグ） =====
  "Aachen": "アーヘン",
  "Aalen": "アーレン",
  "Arminia Bielefeld": "アルミニア・ビーレフェルト",
  "Bochum": "ボーフム",
  "Bremer SV": "ブレーマーSV",
  "Carl Zeiss Jena": "カール・ツァイス・イェーナ",
  "Cottbus": "コットブス",
  "Darmstadt": "ダルムシュタット",
  "Dynamo Dresden": "ダイナモ・ドレスデン",
  "Eintracht Braunschweig": "アイントラハト・ブラウンシュヴァイク",
  "Elversberg": "エルファースベルク",
  "Erzgebirge Aue": "エルツゲビルゲ・アウエ",
  "FC 08 Villingen": "FCヴィリンゲン",
  "FC 93 B-B-G": "FC93",
  "FC Nürnberg": "ニュルンベルク",
  "FC Rouen": "ルーアン",
  "FC Saarbrücken": "ザールブリュッケン",
  "Fortuna Düsseldorf": "フォルトゥナ・デュッセルドルフ",
  "Greifswalder FC": "グライフスヴァルダー",
  "Greuther Fürth": "グロイター・フュルト",
  "Hallescher FC": "ハレッシャー",
  "Hannover": "ハノーファー",
  "Hansa Rostock": "ハンザ・ロストック",
  "Hertha": "ヘルタ",
  "Holstein Kiel": "ホルシュタイン・キール",
  "Ingolstadt": "インゴルシュタット",
  "Jahn Regensburg": "ヤーン・レーゲンスブルク",
  "Kaiserslautern": "カイザースラウテルン",
  "Karlsruhe": "カールスルーエ",
  "Kickers Offenbach": "キッカーズ・オッフェンバッハ",
  "Magdeburg": "マクデブルク",
  "Osnabrück": "オスナブリュック",
  "Paderborn": "パーダーボルン",
  "Phönix Lübeck": "フェニックス・リューベック",
  "Preußen Münster": "プロイセン・ミュンスター",
  "Rot-Weiss Essen": "ロート・ヴァイス・エッセン",
  "SSV Ulm": "SSVウルム",
  "SV Meppen": "SVメッペン",
  "Sandhausen": "ザントハウゼン",
  "Schalke 04": "シャルケ04",
  "Schott Mainz": "ショット・マインツ",
  "Sportfreunde Lotte": "スポルトフロインデ・ロッテ",
  "Teutonia Ottensen": "テウトニア・オッテンゼン",
  "TuS Koblenz": "トゥスコブレンツ",
  "VfV Hildesheim": "ヒルデスハイム",
  "Viktoria Berlin": "ヴィクトリア・ベルリン",
  "Wehen Wiesbaden": "ヴェーエン・ヴィースバーデン",
  "Wuerzburger Kickers": "ヴュルツブルガー・キッカーズ",

  // ===== クープ・ド・フランス（フランス下部リーグ） =====
  "AS Beauvais Oise": "ボーヴェ",
  "AS Dragon": "ドラゴン",
  "AS Vitré": "ヴィトレ",
  "Ajaccio": "アジャクシオ",
  "Amiens": "アミアン",
  "Angoulême": "アングレーム",
  "Annecy": "アヌシー",
  "Arras FA": "アラス",
  "Association Still-Mutzig": "スティル・ミュツィグ",
  "Aubervilliers": "オーベルヴィリエ",
  "Aviron Bayonnais FC": "バイヨンヌ",
  "Bastia": "バスティア",
  "Beaumont Saint-Cyr": "ボーモン・サン・シール",
  "Biesheim": "ビスアイム",
  "Blénod": "ブレノ",
  "Bolbec": "ボルベック",
  "Bordeaux": "ボルドー",
  "Bourgoin-Jallieu": "ブルゴワン・ジャリュー",
  "Boulay": "ブレー",
  "Boulogne": "ブローニュ",
  "C-'Chartres": "シャルトル",
  "Caen": "カーン",
  "Calais Beau Marais": "カレー",
  "Cannes": "カンヌ",
  "Canet Roussillon": "カネ・ルシヨン",
  "Cannet-Rocheville": "カネ・ロシュヴィル",
  "Carnoux": "カルヌー",
  "Cazaux Olympique": "カゾー",
  "Chambéry SF": "シャンベリー",
  "Chaumont": "ショーモン",
  "Clermont Foot": "クレルモン",
  "Cluses-Scionzier FC": "クリューズ",
  "Concarneau": "コンカルノー",
  "Couzeix-Chaptelat": "クゼー",
  "Dijon": "ディジョン",
  "Dinan-Léhon FC": "ディナン",
  "Dives Cabourg": "ディーヴ・カブール",
  "ES Thaon": "タオン",
  "ESA Linas-Montlhéry": "リナ・モンレリー",
  "ESB Marboz": "マルボ",
  "Entente Feignies Aulnoye FC": "フェニー・オルノワ",
  "Epinal": "エピナル",
  "FC Espaly": "エスパリー",
  "FC Fleury 91": "フルーリー",
  "FC Foron": "フォロン",
  "FC Versailles 78": "ヴェルサイユ",
  "FC Villefranche": "ヴィルフランシュ",
  "FCSR Haguenau": "アゲノー",
  "FCSR Obernai": "オベルネ",
  "Feytiat": "フェティア",
  "Freyming": "フレミング",
  "GC Lucciana": "リュッチャーナ",
  "GOAL FC": "ゴールFC",
  "Genouilleux Guéreins Montceaux": "ジュヌイユー",
  "Ginglin-Cesson": "ジャングラン",
  "Grandvillars": "グランヴィラール",
  "Grenoble": "グルノーブル",
  "Gueugnon": "ゲニョン",
  "Guingamp": "ガンガン",
  "Hauts Lyonnais": "オー・リヨネ",
  "Haubourdin": "オーブルダン",
  "Istres": "イストル",
  "JA Drancy": "ドランシー",
  "Jeunesse Evolution": "ジュネス・エヴォリュシオン",
  "Jura Dolois": "ジュラ・ドロワ",
  "Jura Sud Foot": "ジュラ・シュド",
  "L'Union Saint-Jean": "ユニオン・サン・ジャン",
  "La Roche VF": "ラ・ロッシュ",
  "Laval": "ラヴァル",
  "Le Mans": "ル・マン",
  "Le Puy Foot 43": "ル・ピュイ",
  "Le Touquet": "ル・トゥケ",
  "Les Herbiers VF": "レ・ゾルビエ",
  "Liancourt-Clermont": "リアンクール",
  "Lunéville": "リュネヴィル",
  "Marignane Gignac": "マリニャーヌ",
  "Marmande": "マルマンド",
  "Martigues": "マルティーグ",
  "Mérignac": "メリニャック",
  "Nancy": "ナンシー",
  "Neuilly-sur-Marne": "ヌイイ・シュル・マルヌ",
  "Niort": "ニオール",
  "Nousseviller": "ヌスヴィレ",
  "Noyelles-sous-Lens": "ノワイエル",
  "Olympique Alès": "アレス",
  "Olympique Charleville Prix AM": "シャルルヴィル",
  "Olympique Saumur": "ソミュール",
  "Olympique de Valence": "ヴァランス",
  "Orleans": "オルレアン",
  "Paris 15": "パリ15区",
  "Pau FC": "ポーFC",
  "Quevilly": "クヴィリー",
  "RC Calais": "カレー",
  "RCO Agde": "アグド",
  "Raon": "ラオン",
  "Red Star": "レッド・スター",
  "Rodez AF": "ロデス",
  "Ruffiac Malestroit": "リュフィアック",
  "Rumilly-Vallières": "リュミリー",
  "SR Colmar": "コルマール",
  "Sablé FC": "サブレ",
  "Saint-Colomban Sportive Locminé": "サン・コロンバン",
  "Saint-Pierre Milizac": "サン・ピエール・ミリザック",
  "Sarre-Union": "サール・ユニオン",
  "Sochaux": "ソショー",
  "St-Just St-Rambert": "サン・ジュスト",
  "Stade Beaucairois": "ボーケール",
  "Stade Briochin": "サン・ブリユー",
  "Stade Béthunois": "ベテューヌ",
  "Stade de Reims": "ランス",
  "Thionville Lusitanos": "ティオンヴィル",
  "Tour d'Auvergne Rennes": "トゥール・ドーヴェルニュ",
  "Tours": "トゥール",
  "Troyes": "トロワ",
  "UF Mâconnais": "マコネ",
  "US Avranches": "アヴランシュ",
  "US Chantilly": "シャンティイ",
  "US Colomiers Football": "コロミエ",
  "US Monnaie": "モネ",
  "US Montagnarde": "モンタニャルド",
  "US Saint-Malo": "サン・マロ",
  "US Saint-Philbert-de-Grand-Lieu": "サン・フィルベール",
  "USC Corte": "コルト",
  "USL Dunkerque": "ダンケルク",
  "Valence FC": "ヴァランスFC",
  "Valenciennes": "ヴァランシエンヌ",
  "Vannes OC": "ヴァンヌ",
  "Vesoul": "ヴズール",
  "Vierzon": "ヴィエルゾン",
  "Étoile Matoury": "エトワール・マトゥリ",
};

/** チーム名を日本語表記に。未登録時は原語をそのまま返す。 */
export function teamNameJp(rawName: string | null | undefined): string {
  if (!rawName) return "";
  return TEAM_NAME_JP[rawName] ?? rawName;
}

/**
 * リーグ／大会の表示名（カタカナ寄せ）。
 * UEFA 大会の略称は正式表記に展開し、リーグはカタカナ正式名で揃える。
 */
export const LEAGUE_DISPLAY_JP: Record<string, string> = {
  プレミアリーグ: "プレミアリーグ",
  リーガ: "ラ・リーガ",
  セリエA: "セリエA",
  ブンデスリーガ: "ブンデスリーガ",
  リーグアン: "リーグ・アン",
  トルコ: "シュペル・リグ",
  スイス: "スーパー・リーグ",
  オーストリア: "ブンデスリーガ（オーストリア）",
  CL: "チャンピオンズリーグ",
  EL: "ヨーロッパリーグ",
  ECL: "カンファレンスリーグ",
  W杖予選: "ワールドカップ予選",
  EURO: "EURO",
  ネーションズリーグ: "ネーションズリーグ",
  "親善試合/その他": "親善試合",
  // 日本人所属リーグ（直接マッピング）
  "スコティッシュ・プレミアシップ": "スコティッシュ・プレミアシップ",
  "エールディビジ": "エールディビジ",
  "ジュピラー・プロ・リーグ": "ジュピラー・プロ・リーグ",
  "プリメイラ・リーガ": "プリメイラ・リーガ",
  "タサ・デ・ポルトガル": "タサ・デ・ポルトガル",
};

export function leagueDisplayJp(nameJp: string | null | undefined): string {
  if (!nameJp) return "";
  return LEAGUE_DISPLAY_JP[nameJp] ?? nameJp;
}
